@hostname = http://bl.7yue.pro/v1
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@appkey = RdshydjBvcYZhMZC
@bid = 7

### 获取热门书籍(概要)
GET {{hostname}}/book/hot_list
content-type: {{contentType}}
appkey: {{appkey}}

### 获取书籍详细信息
@bid = 7
GET {{hostname}}/book/{{bid}}/detail
content-type: {{contentType}}
appkey: {{appkey}}

### 获取书籍点赞状态

GET {{hostname}}/book/{{bid}}/favor
content-type: {{contentType}}
appkey: {{appkey}}

### 获取书籍短评信息

GET {{hostname}}/book/{{bid}}/short_comment
content-type: {{contentType}}
appkey: {{appkey}}

### 新增短评

POST {{hostname}}/book/add/short_comment
content-type: {{contentType}}
appkey: {{appkey}}

{
  "book_id": {{bid}},
  "content": "新增短评"
}