@hostname = http://bl.7yue.pro/v1
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@appkey = RdshydjBvcYZhMZC


### 获取热门书籍(概要)
GET {{hostname}}/book/hot_list
content-type: {{contentType}}
appkey: {{appkey}}

### 获取当前一期的上一期
GET {{hostname}}/classic/2/previous
content-type: {{contentType}}
appkey: {{appkey}}


### 获取当前一期的下一期
GET {{hostname}}/classic/2/next
content-type: {{contentType}}
appkey: {{appkey}}

